language: ruby
rvm:
- 2.2.0
branches:
  only:
  - develop
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: JBwtas4qNIFiC4EmqZc/ZGL9qnFmuGZRenQR8zfBrxOGeuG1Jo9JQzjS83XiCLKzuOZSXpAbLziXyqi1t6gHCnsD4OT5IDgLFfU2GdczqL6VZFSO83mM6B1nt1ppeFsK4f9bywgFNmVNyp1QoV3AJjqSgMflVKFqC0veafbY84i6ykm3xK108A2ehQ9rjxKEWKPHXjrV8m56k1UrPK3SVOV/V6VmKodrKglcYqw/dm6tvFav4hgQQyZMifuMOYkyeuq5i42ysK7X9qkO98bpW2/wEpCPRBW/JQD7ixKsFgO1RrEoeuL6GMproCjvwwJaXBQrEz3gbs5mP+i4uDAV1lD1be5Lp921euz8UEDjJJvdaCNXzIn+DDOtd/e2WSU6+5F/7/RLrxoGuE8ZVc9wcBZTKJF8yHSQ/OkZ5/VdJRuOOrWRmANe7QA3d47D0t7lag3qom3P2EAcpiBaZw8tp5tZCWX/zo//p+u8DXfmShHhThdhx3umXPq3v0UGGYnfSw0pGXjq+KjYO6OxhkrcWCItQE/pqY/Yx3FJCoMMNFf0L0i1/xRF2a3HKpvUYyGJdJ0c2VbkLpCwANDhUWMafKidU+JC1fUMur7CZu5oA8qtzehqYrqhL0Ev9041h6X9Sf34RxV40XcMOp5W6mBV4tbMtfKz36wPJC6gArtwqqs=
