language: ruby
rvm:
- 2.2.0
branches:
  only:
  - develop
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: pZ63CXk9iwYV/rQYS9NY/yzFNx8PXQv+u088x18pP9mnPsuj4S24dWWyrKEWLPcC+Ud6kRJq+MvgofOUL3TL11zN4evp/sebF5FbbpU5yzQHN0Gw2X16z+hivVR7hVK8J7P5xuKBsxsntA02MAZ373QxQmAZ2Yy0QN0ApPaA/jRanMRJihQ7VVQcehfX7+tDpxql25MrTHh2jOQtRelJHqq5l9wT8ba/Qta/EStX4GinoALH7ZTOLzPOkLBKOM2C3op049XtO3lVklJ8K/EA5oSxd5lEMpDDOZPBMP5JCKOXVs+DURy8hqQoRfGZ+qNEeyVurtfY0mfHNT+MtEn8KcwHkgRZLFKRWw3y+Cd2n+HP55eAvuQMfoB+VBaQJK6+N5Y6h6nvnFyu7gPTs60zscMHAat87AAkNOsUjBPrB8f5E4dEDjaIPO/We8NZRw6+mQ2oikn3uRcHd1n3aqIgJIdC6B78aga5/stZ7vjA+mO1QoB8tmanASK1Bc02B5kmv0wXHH7vqVkF66BVe7wKZuHZsjj5NMFo/ngREQZsUfYNqidqgkv2BEcZND1GGahPIjrJifRK/lg6vZ5wiC9s2SE2SayAp9aAVyqw7TPbMAoOtcPQyHU5EjtHOjLXsCXOgBUYE7LJSXlGGS1RGLfao+GqbaME2MMfha03KCaMVYk=
  - secure: JBwtas4qNIFiC4EmqZc/ZGL9qnFmuGZRenQR8zfBrxOGeuG1Jo9JQzjS83XiCLKzuOZSXpAbLziXyqi1t6gHCnsD4OT5IDgLFfU2GdczqL6VZFSO83mM6B1nt1ppeFsK4f9bywgFNmVNyp1QoV3AJjqSgMflVKFqC0veafbY84i6ykm3xK108A2ehQ9rjxKEWKPHXjrV8m56k1UrPK3SVOV/V6VmKodrKglcYqw/dm6tvFav4hgQQyZMifuMOYkyeuq5i42ysK7X9qkO98bpW2/wEpCPRBW/JQD7ixKsFgO1RrEoeuL6GMproCjvwwJaXBQrEz3gbs5mP+i4uDAV1lD1be5Lp921euz8UEDjJJvdaCNXzIn+DDOtd/e2WSU6+5F/7/RLrxoGuE8ZVc9wcBZTKJF8yHSQ/OkZ5/VdJRuOOrWRmANe7QA3d47D0t7lag3qom3P2EAcpiBaZw8tp5tZCWX/zo//p+u8DXfmShHhThdhx3umXPq3v0UGGYnfSw0pGXjq+KjYO6OxhkrcWCItQE/pqY/Yx3FJCoMMNFf0L0i1/xRF2a3HKpvUYyGJdJ0c2VbkLpCwANDhUWMafKidU+JC1fUMur7CZu5oA8qtzehqYrqhL0Ev9041h6X9Sf34RxV40XcMOp5W6mBV4tbMtfKz36wPJC6gArtwqqs=
